delete from INSTANTCOSTELASTICITYSPACE;
delete from CASCHEDCOMPLETEHISTORICALUSAGE where TIMESTAMPID > 17280;
delete from INSTANTCOSTHISTORY where TIMESTAMPID > 17280;
delete from STRUCTUREDCOLLECTEDDATA where TIMESTAMPID > 17280;
delete from AGGREGATEDDATA where TIMESTAMPID > 17280;
delete from TOTALCOSTHISTORY where TIMESTAMPID > 17280;
delete from TIMESTAMP where ID > 17280;

